version: "2"
linters:
  enable:
    - bodyclose
    - dupword
    - misspell
    - revive
    - unconvert
  disable:
    - errcheck
  exclusions:
    generated: disable
    presets:
      - comments
      - std-error-handling
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: disable
